server:
  port: 8080
  servlet:
    context-path: /myweb
student:
  name: jojo
  age: 20
spring:
  freemarker:
    suffix: .ftl
  datasource:
    url: jdbc:mysql://localhost:3306/myweb?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver